### ISSUE TITLE
Shrimp?

### ISSUE THREAD

**Issue by aaschurr** [carolynfrunyon/LibraryCarpentries#1]
Does it really have to include shrimp?  I occasionally eat seafood, but I'm not a big fan of shrimp.

**Comment by carolynfrunyon** [comment]
Sub for tofu?

**Comment by carolynfrunyon** [comment]
Tempeh?

**Comment by carolynfrunyon** [comment]
Meatless krab?

**Comment by aaschurr** [comment]
Not a fan of tempeh....  But, tofu sounds great!

**Comment by carolynfrunyon** [comment]
Issue closed: https://github.com/carolynfrunyon/LibraryCarpentries/pull/2
